### ISSUE TITLE
KeyError: 'url'

### ISSUE THREAD

**Issue by GrumpyMeow** [fwartner/ha-openwakeword-installer#1]
Hi,
I've just installed this installer. But in the Home Assistant log i see the following error:
```
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:366
integratie: Sensor ([documentatie](https://www.home-assistant.io/integrations/sensor), [problemen](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
Eerst voorgekomen: 17:08:52 (1 gebeurtenissen)
Laatst gelogd: 17:08:52

Error while setting up wakeword_installer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/wakeword_installer/sensor.py", line 18, in async_setup_entry
    repository_url = config_entry.data[CONF_URL]
                     ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'url'
```

I've entered:
* Github repository: `https://github.com/fwartner/home-assistant-wakewords-collection` 
* Folder: `en` 
I've also tried to use the git-repository-url, but that also doesn't work.

**Comment by fwartner** [comment]
Thank you for your report.. Will look into it asap!

**Comment by sopelj** [comment]
It seems to be because the config flow uses `CONF_REPOSITORY_URL` (`repository_url`), but the sensor tries to access it with `CONF_URL` (`url`).

**Comment by IoSonoAndreaZ** [comment]
I did the same and the integration does not seem to work. What it is supposed to happen then?

![Screenshot_20240628_114017](https://github.com/fwartner/ha-openwakeword-installer/assets/45826618/caf08a8f-c0f1-42d1-9e95-98a6e33d6a45)

**Comment by sopelj** [comment]
Maybe check your logs. I also had to manually create the `/share/openwakeword` or it crashed with a "No such file or directory" error. After does both, it properly copies the wake words to `/share/openwakeword`. However, it still does not create any actual entities in the UI.

**Comment by IoSonoAndreaZ** [comment]
```
TypeError: argument of type 'NoneType' is not iterable

2024-06-28 16:16:47.727 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wakeword_installer platform for sensor

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform

    await asyncio.shield(awaitable)

  File "/config/custom_components/wakeword_installer/sensor.py", line 18, in async_setup_entry

    repository_url = config_entry.data[CONF_URL]

                     ~~~~~~~~~~~~~~~~~^^^^^^^^^^
```

**Comment by fwartner** [comment]
Should be fixed now :)

**Comment by IoSonoAndreaZ** [comment]
> Should be fixed now :)

not for me:

Sorry, I had a problem talking to Google Generative AI: 400 * GenerateContentRequest.tools[0].function_declarations[20].parameters.properties[orario].format: only 'enum' is supported for STRING type
* GenerateContentRequest.tools[0].function_declarations[21].parameters.properties[tempo].type: must be specified

using core version 2024.7.3 with docker.

basically we can't use Gemini since two weeks

**Comment by fwartner** [comment]
Uhm.. This repository has *nothing* to do with Gemeni at all. It´s only related to openwakewords.

**Comment by IoSonoAndreaZ** [comment]
> Uhm.. This repository has _nothing_ to do with Gemeni at all. It´s only related to openwakewords.

sorry my mistake
