### ISSUE TITLE
Unable to install via HACS

### ISSUE THREAD

**Issue by deltabert** [fwartner/ha-openwakeword-installer#2]
Hi Florian,
I try to install your openwakeword-installer via HACS (using category Integrations), but i get this error message:
GitHub returned 404 for https://api.github.com/repos/your-repo/openwakeword

Further I noticed by the Manual Installation that i should download teh openwakeword directory, but i see only a directory openwakeword-installer.  Maybe the Readme has to be updated... ?

BTW, i used Chrome and Edge to install your Integration.

**Comment by fwartner** [comment]
![image](https://github.com/fwartner/ha-openwakeword-installer/assets/6692500/03a20107-7cfb-40a7-976e-a51ce88db367)

This is whats coming when i use my wakewords repository: https://github.com/fwartner/home-assistant-wakewords-collection

Please notice that "https://github.com/your-repo/openwakeword" from the README isnt a real repo 😆 
I thought that would be clear.. ^^

**Comment by fwartner** [comment]
Please use https://github.com/fwartner/ha-openwakeword-installer as the right url.

**Comment by fwartner** [comment]
I also updated the readme.. Sorry for the confusion.
