### ISSUE TITLE
Mistake during installation

### ISSUE THREAD

**Issue by Elbredde** [fwartner/ha-openwakeword-installer#3]
![Fehlermeldung wakewordinstaller](https://github.com/fwartner/ha-openwakeword-installer/assets/65981021/1dc082a9-1c3b-4e9a-ad99-67e629556a5f)

Hi, I downloaded the Repository via HACS and restarted homeassistant. When I wanted to install the integration I received the attached message

Fehler: Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

can you help me to solve this?

**Comment by fwartner** [comment]
Working on it right now :)

**Comment by Elbredde** [comment]
Hi, I have the Repositaroy "openwakeword" installed on HA, as I just would like to use the R2D2 wakeword, do you think it will work if I just safe your r2d2 files in the relevant HA folder?
