### ISSUE TITLE
Permission denied on creating directory in root folder

### ISSUE THREAD

**Issue by daniele-athome** [fwartner/ha-openwakeword-installer#6]
Latest HACS version on Home Assistant Core install - so no container, just plain Python running in a virtualenv.

```
Error during setup of component wakeword_installer
Traceback (most recent call last):
  File "/home/homeassistant/hass/lib/python3.12/site-packages/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/wakeword_installer/__init__.py", line 17, in async_setup
    await hass.async_add_executor_job(create_directory, '/share/openwakeword')
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/wakeword_installer/__init__.py", line 52, in create_directory
    os.makedirs(path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/share'
```

**Comment by fwartner** [comment]
Works now. Thank you for mentioning this issue! :)

**Comment by daniele-athome** [comment]
No problem. Is the directory needed to the integration? I see you still try to create it in the code with the same path.

**Comment by fwartner** [comment]
Since the wakewords will be loaded from `/share/openwakeword`, the path is needed. :)

**Comment by daniele-athome** [comment]
Ok so I don't think it'll work outside of a container. I run HA as a standalone service directly in the host system, so no root privileges and no dedicated root file system.
You should use maybe a relative path (HA should start its process with the configuration directory as its cwd) or maybe ask for it at configuration time.

**Comment by fwartner** [comment]
Please refer to the official guides by homeassistant in order to install openwakewords. ^^
This integration does only install wakewords from repositories like my https://github.com/fwartner/home-assistant-wakewords-collection. :)

**Comment by daniele-athome** [comment]
Sorry maybe I wasn't clear - or I am missing something probably. The guides take for granted a container-based or HAOS installation. Some of us run HA directly in the host OS, without containers, so no addons, no share directory etc.
